version: '3.8'

services:
  ###> Web service (Symfony + PHP) ###
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
      - mailer
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://user:userpassword@database:3306/escalada_db?serverVersion=10.6&charset=utf8mb4"
      MAILER_DSN: smtp://mailer:1025
    entrypoint: ["/var/www/html/docker/entrypoint.sh"]

  ###> MariaDB service ###
#  database:
#    image: mariadb:10.6
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpassword
#      MYSQL_DATABASE: escalada_db
#      MYSQL_USER: user
#      MYSQL_PASSWORD: userpassword
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "--silent"]
#      retries: 5
#      start_period: 30s
#    volumes:
#      - database_data:/var/lib/mysql
#      - ./docker/escalada_db.sql:/docker-entrypoint-initdb.d/escalada_db.sql
#    command: --skip-ssl

  ###> Mailer (MailHog) ###
  mailer:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  ###> Nginx service ###
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web

  ###> Adminer service ###
  adminer:
    image: adminer
    ports:
      - "8082:8080"
    depends_on:
      - database

volumes:
  database_data:
